server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${db.url:jdbc:mysql://localhost:3307/notion}
    username: ${db.username:root}
    password: ${db.password:root}


#  flyway:
#    enabled: true

